version: "3"
services:
 vulnapp-secure:
  build: ./
  container_name: vulnapp-secure
  ports:
   - 5100:5000
  environment:
   - vulnerable=0

 vulnapp-vulnerable:
  build: ./
  container_name: vulnapp-vulnerable
  ports:
   - 5200:5000
  environment:
   - vulnerable=1
